-- ============================================================
-- MARGEMAX - MIGRATION NON DESTRUCTIVE
-- Preuve de consentement "execution immediate + renonciation au droit
-- de retractation" (art. L.221-28 du Code de la consommation), enregistree
-- cote serveur AVANT toute redirection vers un Payment Link Stripe.
-- A executer UNE FOIS dans Supabase SQL Editor.
-- Ne supprime aucune table ni donnee existante.
-- ============================================================

create table if not exists public.checkout_consents (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    pack_key text not null,
    cgv_version text not null,
    consented_at timestamptz not null default now()
);
alter table public.checkout_consents enable row level security;

-- Preuve juridique : lecture par son propriétaire uniquement, aucune
-- politique update/delete (un consentement enregistré ne doit jamais être
-- modifié ni effacé après coup).
drop policy if exists "checkout_consents_select_own" on public.checkout_consents;
create policy "checkout_consents_select_own" on public.checkout_consents
for select using (auth.uid() = user_id);

drop policy if exists "checkout_consents_insert_own" on public.checkout_consents;
create policy "checkout_consents_insert_own" on public.checkout_consents
for insert with check (auth.uid() = user_id);

create index if not exists checkout_consents_user_id_idx
    on public.checkout_consents (user_id);
