-- ============================================================
-- MARGEMAX - MIGRATION NON DESTRUCTIVE
-- Carnet de Sourcing + Notes libres + Comparateur de Produits
-- A executer UNE FOIS dans Supabase SQL Editor.
-- Ne supprime aucune table ni donnee existante (uniquement des
-- "create table if not exists" et des policies recreees a l'identique).
-- ============================================================

-- ============================================================
-- CARNET DE SOURCING -- "Produits à suivre" (par utilisateur)
-- ============================================================
create table if not exists public.sourcing_notebook (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    product_id text,
    product_name text,
    product_url text,
    image_url text,
    purchase_price numeric,
    shipping_price numeric,
    sale_price numeric,
    margin_value numeric,
    margin_percent numeric,
    status text not null default 'a_etudier',
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.sourcing_notebook enable row level security;

drop policy if exists "notebook_select_own" on public.sourcing_notebook;
create policy "notebook_select_own" on public.sourcing_notebook
for select using (auth.uid() = user_id);

drop policy if exists "notebook_insert_own" on public.sourcing_notebook;
create policy "notebook_insert_own" on public.sourcing_notebook
for insert with check (auth.uid() = user_id);

drop policy if exists "notebook_update_own" on public.sourcing_notebook;
create policy "notebook_update_own" on public.sourcing_notebook
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "notebook_delete_own" on public.sourcing_notebook;
create policy "notebook_delete_own" on public.sourcing_notebook
for delete using (auth.uid() = user_id);

-- ============================================================
-- NOTES LIBRES PAR UTILISATEUR (Carnet de Sourcing + Calculateur de Marge)
-- 'kind' distingue les usages : 'carnet' (notes de sourcing) vs
-- 'calculateur' (notes de marge) -- meme table, pas de table separee
-- necessaire. Une seule note par utilisateur et par 'kind' (upsert sur
-- ce couple, voir la contrainte unique ci-dessous).
-- ============================================================
create table if not exists public.user_notes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    kind text not null default 'carnet',
    content text,
    updated_at timestamptz not null default now(),
    unique (user_id, kind)
);
alter table public.user_notes enable row level security;

drop policy if exists "user_notes_select_own" on public.user_notes;
create policy "user_notes_select_own" on public.user_notes
for select using (auth.uid() = user_id);

drop policy if exists "user_notes_insert_own" on public.user_notes;
create policy "user_notes_insert_own" on public.user_notes
for insert with check (auth.uid() = user_id);

drop policy if exists "user_notes_update_own" on public.user_notes;
create policy "user_notes_update_own" on public.user_notes
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "user_notes_delete_own" on public.user_notes;
create policy "user_notes_delete_own" on public.user_notes
for delete using (auth.uid() = user_id);

-- ============================================================
-- COMPARATEUR DE PRODUITS (par utilisateur) -- utilise a la fois depuis
-- le Carnet de Sourcing et depuis le Calculateur de Marge (meme table,
-- meme structure de comparaison cote a cote). 'source_context' distingue
-- les deux comparatifs (chacun garde le sien, l'un n'ecrase pas l'autre).
-- ============================================================
create table if not exists public.product_comparisons (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    source_context text not null default 'carnet',
    product_name text,
    purchase_price numeric,
    shipping_price numeric,
    other_costs numeric,
    vat_percent numeric,
    payment_fee_percent numeric,
    sale_price numeric,
    margin_value numeric,
    margin_percent numeric,
    roi_percent numeric,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.product_comparisons enable row level security;

drop policy if exists "comparisons_select_own" on public.product_comparisons;
create policy "comparisons_select_own" on public.product_comparisons
for select using (auth.uid() = user_id);

drop policy if exists "comparisons_insert_own" on public.product_comparisons;
create policy "comparisons_insert_own" on public.product_comparisons
for insert with check (auth.uid() = user_id);

drop policy if exists "comparisons_update_own" on public.product_comparisons;
create policy "comparisons_update_own" on public.product_comparisons
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "comparisons_delete_own" on public.product_comparisons;
create policy "comparisons_delete_own" on public.product_comparisons
for delete using (auth.uid() = user_id);
