-- ============================================================
-- MARGEMAX - Webhook Stripe : tables, fonction de credit et droits
-- A executer UNE FOIS dans Supabase -> SQL Editor (idempotent, non
-- destructif). A lancer si le webhook Stripe repond HTTP 500 avec
-- {"error":"erreur serveur"} : cela signifie que la table
-- stripe_webhook_events (ou credit_purchases / add_credits) n'existe pas
-- dans ta base.
-- ============================================================

-- Client Stripe du profil (portail de facturation).
alter table public.profiles add column if not exists stripe_customer_id text;
create unique index if not exists profiles_stripe_customer_id_key
  on public.profiles (stripe_customer_id)
  where stripe_customer_id is not null;

-- Colonnes de credits (au cas ou).
alter table public.profiles add column if not exists credits integer not null default 3;
alter table public.profiles add column if not exists credits_gauge_max integer not null default 3;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

-- Idempotence : un evenement Stripe n'est jamais traite deux fois.
create table if not exists public.stripe_webhook_events (
    id text primary key,
    type text not null,
    processed_at timestamptz not null default now()
);
alter table public.stripe_webhook_events enable row level security;

-- Trace de chaque achat credite (contrainte unique = 2e filet d'idempotence).
create table if not exists public.credit_purchases (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    pack_key text not null,
    credits integer not null,
    amount_total integer not null,
    currency text not null,
    stripe_session_id text not null unique,
    created_at timestamptz not null default now()
);
alter table public.credit_purchases enable row level security;

drop policy if exists "credit_purchases_select_own" on public.credit_purchases;
create policy "credit_purchases_select_own" on public.credit_purchases
for select using (auth.uid() = user_id);

-- Credit atomique apres paiement confirme (appelee par le webhook).
create or replace function public.add_credits(p_user_id uuid, p_amount integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_amount <= 0 then
    raise exception 'add_credits: p_amount doit etre positif';
  end if;

  update public.profiles
  set credits = credits + p_amount,
      updated_at = now()
  where id = p_user_id;

  if not found then
    raise exception 'add_credits: profil % introuvable', p_user_id;
  end if;
end;
$$;

-- SECURITE : par defaut Postgres autorise EXECUTE a tout le monde. Sans ces
-- lignes, n'importe quel utilisateur connecte pourrait appeler add_credits
-- depuis le navigateur pour se donner des credits. Seule la service_role
-- (webhook, cote serveur) doit pouvoir l'executer.
revoke all on function public.add_credits(uuid, integer) from public;
revoke all on function public.add_credits(uuid, integer) from anon;
revoke all on function public.add_credits(uuid, integer) from authenticated;
grant execute on function public.add_credits(uuid, integer) to service_role;

-- Acces de la service_role aux tables du webhook.
grant all on table public.stripe_webhook_events to service_role;
grant all on table public.credit_purchases to service_role;

notify pgrst, 'reload schema';
