-- ============================================================
-- MARGEMAX - MIGRATION PRODUCTION NON DESTRUCTIVE
-- A exécuter UNE FOIS dans Supabase SQL Editor.
-- Ne supprime aucune donnée existante.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    plan text not null default 'free',
    searches_used integer not null default 0,
    plan_expires_at timestamptz,
    is_admin boolean not null default false,
    is_suspended boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists plan text not null default 'free';
alter table public.profiles add column if not exists searches_used integer not null default 0;
alter table public.profiles add column if not exists plan_expires_at timestamptz;
alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists is_suspended boolean not null default false;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.search_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    query text not null,
    result_count integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.favoris (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    product_id text,
    title text,
    image_url text,
    product_url text,
    purchase_price numeric,
    shipping_price numeric,
    seller_score numeric,
    potential_score numeric,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.search_history enable row level security;
alter table public.favoris enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "history_select_own" on public.search_history;
create policy "history_select_own" on public.search_history
for select using (auth.uid() = user_id);

drop policy if exists "history_insert_own" on public.search_history;
create policy "history_insert_own" on public.search_history
for insert with check (auth.uid() = user_id);

drop policy if exists "favoris_select_own" on public.favoris;
create policy "favoris_select_own" on public.favoris
for select using (auth.uid() = user_id);

drop policy if exists "favoris_insert_own" on public.favoris;
create policy "favoris_insert_own" on public.favoris
for insert with check (auth.uid() = user_id);

drop policy if exists "favoris_delete_own" on public.favoris;
create policy "favoris_delete_own" on public.favoris
for delete using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, plan, searches_used)
  values (new.id, new.email, 'free', 0)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_margemax on auth.users;
create trigger on_auth_user_created_margemax
after insert on auth.users
for each row execute procedure public.handle_new_user();
