-- ============================================================
-- MARGEMAX - MIGRATION PRODUCTION NON DESTRUCTIVE
-- A exécuter UNE FOIS dans Supabase SQL Editor.
-- Ne supprime aucune donnée existante.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    plan text not null default 'free',
    searches_used integer not null default 0,
    plan_expires_at timestamptz,
    is_admin boolean not null default false,
    is_suspended boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists plan text not null default 'free';
alter table public.profiles add column if not exists searches_used integer not null default 0;
alter table public.profiles add column if not exists plan_expires_at timestamptz;
alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists is_suspended boolean not null default false;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

-- ============================================================
-- MIGRATION CRÉDITS PRÉPAYÉS (remplace le modèle d'abonnement)
-- 'plan' / 'plan_expires_at' restent en base (non supprimées, pour ne rien
-- casser) mais ne sont plus utilisées par l'application.
-- Le défaut "3" s'applique aussi bien aux lignes existantes (backfill
-- immédiat) qu'aux futures lignes insérées par le trigger handle_new_user
-- ci-dessous, qui ne mentionne pas ces colonnes.
-- ============================================================
alter table public.profiles add column if not exists credits integer not null default 3;
alter table public.profiles add column if not exists credits_gauge_max integer not null default 3;

create table if not exists public.search_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    query text not null,
    result_count integer not null default 0,
    created_at timestamptz not null default now()
);

-- Statut de chaque recherche (succes / aucun_resultat / erreur), pour
-- affichage dans l'historique. Les lignes existantes (creees avant cette
-- colonne) sont considerees "succes" par defaut, seule valeur cohérente
-- avec le fait qu'elles avaient deja un result_count > 0 a l'epoque.
alter table public.search_history add column if not exists status text not null default 'succes';

-- ============================================================
-- CONFIGURATION APPLICATIVE PARTAGEE (ex: tokens OAuth AliExpress)
-- Cle/valeur, accessible uniquement via la service_role key (jamais
-- exposee au client) -- pas de RLS "self" possible ici car ce n'est pas
-- une donnee par utilisateur, mais partagee par toute l'application.
-- ============================================================
create table if not exists public.app_config (
    key text primary key,
    value text,
    updated_at timestamptz not null default now()
);
alter table public.app_config enable row level security;
-- Aucune policy select/insert/update pour les roles authenticated/anon :
-- cette table n'est lisible/modifiable que via la service_role key,
-- utilisee uniquement cote serveur (jamais depuis le navigateur).

create table if not exists public.favoris (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    product_id text,
    title text,
    image_url text,
    product_url text,
    purchase_price numeric,
    shipping_price numeric,
    seller_score numeric,
    potential_score numeric,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.search_history enable row level security;
alter table public.favoris enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "history_select_own" on public.search_history;
create policy "history_select_own" on public.search_history
for select using (auth.uid() = user_id);

drop policy if exists "history_insert_own" on public.search_history;
create policy "history_insert_own" on public.search_history
for insert with check (auth.uid() = user_id);

drop policy if exists "favoris_select_own" on public.favoris;
create policy "favoris_select_own" on public.favoris
for select using (auth.uid() = user_id);

drop policy if exists "favoris_insert_own" on public.favoris;
create policy "favoris_insert_own" on public.favoris
for insert with check (auth.uid() = user_id);

drop policy if exists "favoris_delete_own" on public.favoris;
create policy "favoris_delete_own" on public.favoris
for delete using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, plan, searches_used)
  values (new.id, new.email, 'free', 0)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_margemax on auth.users;
create trigger on_auth_user_created_margemax
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ============================================================
-- CARNET DE SOURCING -- "Produits à suivre" (par utilisateur)
-- ============================================================
create table if not exists public.sourcing_notebook (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    product_id text,
    product_name text,
    product_url text,
    image_url text,
    purchase_price numeric,
    shipping_price numeric,
    sale_price numeric,
    margin_value numeric,
    margin_percent numeric,
    status text not null default 'a_etudier',
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.sourcing_notebook enable row level security;

drop policy if exists "notebook_select_own" on public.sourcing_notebook;
create policy "notebook_select_own" on public.sourcing_notebook
for select using (auth.uid() = user_id);

drop policy if exists "notebook_insert_own" on public.sourcing_notebook;
create policy "notebook_insert_own" on public.sourcing_notebook
for insert with check (auth.uid() = user_id);

drop policy if exists "notebook_update_own" on public.sourcing_notebook;
create policy "notebook_update_own" on public.sourcing_notebook
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "notebook_delete_own" on public.sourcing_notebook;
create policy "notebook_delete_own" on public.sourcing_notebook
for delete using (auth.uid() = user_id);

-- ============================================================
-- NOTES LIBRES PAR UTILISATEUR (Carnet de Sourcing + Calculateur de Marge)
-- 'kind' distingue les usages : 'carnet' (notes de sourcing) vs
-- 'calculateur' (notes de marge) -- meme table, pas de table separee
-- necessaire. Une seule note par utilisateur et par 'kind' (upsert sur
-- ce couple, voir la contrainte unique ci-dessous).
-- ============================================================
create table if not exists public.user_notes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    kind text not null default 'carnet',
    content text,
    updated_at timestamptz not null default now(),
    unique (user_id, kind)
);
alter table public.user_notes enable row level security;

drop policy if exists "user_notes_select_own" on public.user_notes;
create policy "user_notes_select_own" on public.user_notes
for select using (auth.uid() = user_id);

drop policy if exists "user_notes_insert_own" on public.user_notes;
create policy "user_notes_insert_own" on public.user_notes
for insert with check (auth.uid() = user_id);

drop policy if exists "user_notes_update_own" on public.user_notes;
create policy "user_notes_update_own" on public.user_notes
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "user_notes_delete_own" on public.user_notes;
create policy "user_notes_delete_own" on public.user_notes
for delete using (auth.uid() = user_id);

-- ============================================================
-- COMPARATEUR DE PRODUITS (par utilisateur) -- utilise a la fois depuis
-- le Carnet de Sourcing et depuis le Calculateur de Marge (meme table,
-- meme structure de comparaison cote a cote).
-- ============================================================
create table if not exists public.product_comparisons (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    -- 'carnet' (Carnet de Sourcing) ou 'calculateur' (Calculateur de
    -- Marge) : les deux pages partagent cette table mais gardent chacune
    -- leur propre comparatif independant (sinon enregistrer depuis l'une
    -- ecraserait le comparatif de l'autre).
    source_context text not null default 'carnet',
    product_name text,
    purchase_price numeric,
    shipping_price numeric,
    other_costs numeric,
    vat_percent numeric,
    payment_fee_percent numeric,
    sale_price numeric,
    margin_value numeric,
    margin_percent numeric,
    roi_percent numeric,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.product_comparisons enable row level security;

drop policy if exists "comparisons_select_own" on public.product_comparisons;
create policy "comparisons_select_own" on public.product_comparisons
for select using (auth.uid() = user_id);

drop policy if exists "comparisons_insert_own" on public.product_comparisons;
create policy "comparisons_insert_own" on public.product_comparisons
for insert with check (auth.uid() = user_id);

drop policy if exists "comparisons_update_own" on public.product_comparisons;
create policy "comparisons_update_own" on public.product_comparisons
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "comparisons_delete_own" on public.product_comparisons;
create policy "comparisons_delete_own" on public.product_comparisons
for delete using (auth.uid() = user_id);

-- ============================================================
-- CREDITS ATOMIQUES + WEBHOOK STRIPE (idempotence)
-- A executer sur le NOUVEAU projet Supabase (voir .env.example) : une
-- reinitialisation Supabase ne conserve ni tables, ni policies, ni
-- triggers -- tout le fichier doit etre rejoue, pas seulement cette
-- section.
-- ============================================================

-- Un evenement Stripe (event.id, ex. evt_1Nx...) ne doit jamais etre
-- traite deux fois, meme si Stripe le renvoie plusieurs fois (retries
-- de webhook). Cle primaire sur l'id Stripe = rejet automatique d'un
-- doublon par la contrainte, sans logique applicative fragile.
create table if not exists public.stripe_webhook_events (
    id text primary key,
    type text not null,
    processed_at timestamptz not null default now()
);
alter table public.stripe_webhook_events enable row level security;
-- Aucune policy select/insert : accessible uniquement via la
-- service_role key, utilisee uniquement par app/api/webhooks/stripe.

-- Trace de chaque credit de pack reussi -- verification manuelle
-- possible (montant, devise, pack, utilisateur) et deuxieme filet
-- d'idempotence via la contrainte unique sur stripe_session_id : meme
-- si stripe_webhook_events etait contourne, un meme Checkout Session
-- ne peut pas crediter deux fois.
create table if not exists public.credit_purchases (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    pack_key text not null,
    credits integer not null,
    amount_total integer not null,
    currency text not null,
    stripe_session_id text not null unique,
    created_at timestamptz not null default now()
);
alter table public.credit_purchases enable row level security;

drop policy if exists "credit_purchases_select_own" on public.credit_purchases;
create policy "credit_purchases_select_own" on public.credit_purchases
for select using (auth.uid() = user_id);
-- Aucune policy insert : uniquement via la service_role key (webhook).

-- Credit atomique (paiement confirme) -- appelee uniquement par le
-- webhook via la service_role key, jamais depuis le client.
create or replace function public.add_credits(p_user_id uuid, p_amount integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_amount <= 0 then
    raise exception 'add_credits: p_amount doit etre positif';
  end if;

  update public.profiles
  set credits = credits + p_amount,
      updated_at = now()
  where id = p_user_id;

  if not found then
    raise exception 'add_credits: profil % introuvable', p_user_id;
  end if;
end;
$$;

-- Debit atomique d'un credit (1 analyse). "where credits > 0" dans le
-- meme UPDATE empeche tout solde negatif meme sous requetes
-- concurrentes -- Postgres verrouille la ligne le temps de la mise a
-- jour, pas besoin de SELECT...FOR UPDATE separe. Retourne le nouveau
-- solde si le debit a eu lieu, NULL si le solde etait deja a 0.
-- security definer + verification interne de auth.uid() : appelable
-- par l'utilisateur authentifie lui-meme (client Supabase serveur
-- normal, pas la service_role key), jamais pour le compte d'un tiers.
create or replace function public.consume_credit(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_balance integer;
begin
  if auth.uid() is distinct from p_user_id then
    raise exception 'consume_credit: non autorise pour cet utilisateur';
  end if;

  update public.profiles
  set credits = credits - 1,
      updated_at = now()
  where id = p_user_id
    and credits > 0
  returning credits into v_new_balance;

  return v_new_balance;
end;
$$;

grant execute on function public.consume_credit(uuid) to authenticated;
